import { test, expect, type Page } from '@playwright/test'
import { productAction } from './product-helpers'

async function navigate(page: Page, name: string) { await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name, exact: true }).click() }
async function tools(page: Page, name: string) { await page.getByRole('button', { name: 'Store tools', exact: true }).click(); await page.getByLabel('Choose a store tool').selectOption(name) }
async function scan(page: Page) { const input = page.getByRole('textbox', { name: 'Scan or enter barcode' }); await input.fill('4800016000013'); await input.press('Enter') }
async function attemptArchive(page: Page) {
  await page.getByRole('button', { name: 'Close day', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel(/I exported a backup/).check()
  await dialog.getByRole('button', { name: 'Close day & download', exact: true }).click()
}
test.beforeEach(async ({ page }) => { await page.clock.install(); await page.goto('/'); await expect(page.getByRole('button', { name: /^Coca-Cola Original/ })).toBeVisible() })

test('low-stock banner drafts a purchase and receiving clears the alert', async ({ page }) => {
  await navigate(page, 'Products'); await productAction(page, 'Adjust stock')
  await page.getByRole('spinbutton', { name: 'New stock quantity', exact: true }).fill('4')
  await page.getByRole('button', { name: 'Save stock adjustment', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await navigate(page, 'Sell')
  await page.getByRole('button', { name: '1 product is low on stock', exact: true }).click()
  await expect(page.getByText('Add a supplier to continue your low-stock purchase.')).toBeVisible()
  await page.getByRole('button', { name: 'Add supplier', exact: true }).click()
  await page.getByRole('textbox', { name: 'Supplier name', exact: true }).fill('Wholesale shop')
  await page.getByRole('button', { name: 'Save supplier', exact: true }).click()
  const draft = page.getByRole('dialog', { name: 'New purchase order', exact: true })
  await expect(draft).toBeVisible()
  await expect(draft.getByRole('spinbutton', { name: 'Purchase quantity: Coca-Cola Original', exact: true })).toHaveValue('6')
  await draft.getByRole('spinbutton', { name: 'Unit cost: Coca-Cola Original', exact: true }).fill('15')
  await draft.getByRole('button', { name: 'Create purchase order', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.reload()
  await tools(page, 'Purchasing')
  await page.getByRole('button', { name: 'Receive purchase', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByText('received · ₱90.00', { exact: true })).toBeVisible()
  await navigate(page, 'Sell')
  await expect(page.getByRole('button', { name: /low on stock/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /^Coca-Cola Original/ })).toContainText('10 in stock')
})

test('cash differences block day close until reviewed and remain visible after reload', async ({ page }) => {
  await tools(page, 'Cash drawer'); await page.getByRole('button', { name: 'Open cash shift', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Open shift #1' })).toBeVisible()
  await navigate(page, 'Sell'); await scan(page)
  await page.getByRole('button', { name: 'Checkout', exact: true }).click()
  await page.getByRole('button', { name: 'Complete sale', exact: true }).click()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await attemptArchive(page)
  await expect(page.getByRole('alert')).toContainText('Count and close')
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await tools(page, 'Cash drawer'); await page.getByRole('button', { name: 'Close cash shift', exact: true }).click()
  await page.getByLabel('Counted cash (₱)').fill('24')
  await page.getByRole('button', { name: 'Save closing cash count', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.reload()
  const reviewAlert = page.getByRole('button', { name: 'Shift #1: -₱1.00 cash difference needs review', exact: true })
  await expect(reviewAlert).toBeVisible()
  await attemptArchive(page)
  await expect(page.getByRole('alert')).toContainText('Review cash differences')
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await reviewAlert.click()
  await page.getByRole('button', { name: 'Review cash difference', exact: true }).click()
  await page.getByLabel('Variance review note').fill('Drawer recounted; shortage recorded')
  await page.getByRole('button', { name: 'Confirm variance review', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await navigate(page, 'Sell'); await expect(reviewAlert).toHaveCount(0)
  const download = page.waitForEvent('download')
  await attemptArchive(page); await download
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('storage polling blocks an open checkout, keeps export available, and resumes below the threshold', async ({ page }) => {
  await scan(page); await page.getByRole('button', { name: 'Checkout', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Complete sale', exact: true })).toBeEnabled()
  await page.evaluate(() => { Object.defineProperty(navigator.storage, 'estimate', { configurable: true, value: async () => ({ usage: 81, quota: 100 }) }) })
  await page.clock.fastForward(15001)
  await expect(page.getByRole('button', { name: 'Complete sale', exact: true })).toBeDisabled()
  await page.getByRole('dialog').getByRole('button', { name: 'Export full backup', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
  await page.locator('section').filter({ has: page.getByRole('heading', { name: 'Backups and storage', exact: true }) }).getByRole('button', { name: 'Export full backup', exact: true }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download backup', exact: true }).click(); await download
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await navigate(page, 'Sell')
  await page.getByRole('button', { name: 'Checkout', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
  await page.evaluate(() => { Object.defineProperty(navigator.storage, 'estimate', { configurable: true, value: async () => ({ usage: 80, quota: 100 }) }) })
  await page.clock.fastForward(15001)
  await expect(page.locator('.backup-notice').filter({ hasText: 'over 80%' })).toHaveCount(0)
  await navigate(page, 'Sell'); await page.getByRole('button', { name: 'Checkout', exact: true }).click()
  await page.getByRole('button', { name: 'Complete sale', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Receipt #000001' })).toBeVisible()
})
