import { test, expect } from '@playwright/test'
import { productAction } from './product-helpers'

for (const width of [320, 412]) {
  test(`phone product cards have separated details and reachable actions at ${width}px`, async ({ page, isMobile }) => {
    test.skip(!isMobile, 'Phone product layout')
    await page.setViewportSize({ width, height: 800 })
    await page.goto('/')
    await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Products', exact: true }).click()
    const product = page.getByRole('row').filter({ hasText: 'Coca-Cola Original' })
    await expect(product).toBeVisible()
    const name = await product.locator('strong').boundingBox()
    const barcode = await product.locator('.product-barcode').boundingBox()
    const category = await product.locator('.product-category').boundingBox()
    expect(barcode!.y).toBeGreaterThanOrEqual(name!.y + name!.height)
    expect(category!.y).toBeGreaterThanOrEqual(barcode!.y + barcode!.height)
    const manage = product.getByRole('button', { name: 'Manage Coca-Cola Original', exact: true })
    expect((await manage.boundingBox())!.height).toBeGreaterThanOrEqual(48)
    await expect(product.getByRole('button')).toHaveCount(1)
    await page.screenshot({ path: `test-results/products-spaced-${width}.png`, fullPage: true })
    await productAction(page, 'Edit')
    await expect(page.getByRole('dialog').getByRole('textbox', { name: 'Product name', exact: true })).toHaveValue('Coca-Cola Original')
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await productAction(page, 'Adjust stock')
    await page.getByRole('spinbutton', { name: 'New stock quantity', exact: true }).fill('4')
    await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Delivery of four units')
    await page.getByRole('button', { name: 'Save stock adjustment', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(product).toContainText('4 · Low')
    await productAction(page, 'Delete')
    await expect(page.getByRole('dialog')).toHaveAccessibleName('Delete product?')
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(manage).toBeVisible()
    await productAction(page, 'Delete')
    await page.getByRole('dialog').getByRole('button', { name: 'Delete product', exact: true }).click()
    await expect(manage).toHaveCount(0)
    await expect(page.locator('.app-shell')).not.toHaveAttribute('inert', '')
    await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name: 'Sell', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Sell', exact: true })).toBeVisible()
  })
}
