import { test, expect, type Page } from '@playwright/test'
import { productAction } from './product-helpers'

const code = '4800016000013'
async function navigate(page: Page, name: string) { await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name, exact: true }).click() }
async function tools(page: Page, name: string) { await page.getByRole('button', { name: 'Store tools', exact: true }).click(); await page.getByLabel('Choose a store tool').selectOption(name) }
async function scan(page: Page) { const input = page.getByRole('textbox', { name: 'Scan or enter barcode' }); await input.fill(code); await input.press('Enter') }
test.beforeEach(async ({ page }) => { await page.goto('/'); await expect(page.getByRole('button', { name: /^Coca-Cola Original/ })).toBeVisible() })

test('customers, discounts, added tax, split payments, partial refunds and loyalty agree', async ({ page }) => {
  await tools(page, 'Customers'); await page.getByRole('button', { name: 'Add customer', exact: true }).click(); await page.getByRole('textbox', { name: 'Customer name', exact: true }).fill('Ana'); await page.getByLabel('Loyalty card barcode').fill('ANA-001'); await page.getByRole('button', { name: 'Save customer', exact: true }).click()
  await tools(page, 'Checkout settings'); await page.getByRole('combobox', { name: 'Tax mode', exact: true }).selectOption('added'); await page.getByRole('spinbutton', { name: 'Tax rate (%)', exact: true }).fill('12'); await page.getByLabel('Loyalty earning rate (%)').fill('5'); await page.getByRole('button', { name: 'Save checkout settings' }).click()
  await navigate(page, 'Sell'); await scan(page); await scan(page); await page.getByRole('button', { name: 'Checkout', exact: true }).click(); const dialog = page.getByRole('dialog'); await dialog.getByText('Customer, discounts, tax, and order details', { exact: true }).click(); await dialog.getByRole('combobox', { name: 'Customer', exact: true }).selectOption({ label: 'Ana' }); await dialog.getByLabel('Order discount value').fill('5'); await dialog.getByLabel('Payment method').selectOption('split'); await dialog.getByLabel('Cash part (₱)').fill('20'); await dialog.getByLabel('Reference number (optional)').fill('REF12345'); await expect(dialog.getByLabel('Amount received (₱)')).toHaveValue('50.40'); await dialog.getByRole('button', { name: 'Complete sale', exact: true }).click(); await expect(dialog.getByRole('heading', { name: /Receipt #/ })).toBeVisible(); await expect(dialog).toContainText('Points earned: 2.25'); await expect(dialog).toContainText('₱50.40'); await expect(dialog).toContainText('REF12345'); await dialog.getByRole('button', { name: 'Done', exact: true }).click()
  await navigate(page, 'Sales history'); await page.getByRole('button', { name: 'Void / refund 1', exact: true }).click(); await page.getByRole('spinbutton', { name: 'Refund quantity: Coca-Cola Original', exact: true }).fill('1'); await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('One bottle returned'); await page.getByRole('button', { name: 'Record correction' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByText('Partly refunded', { exact: true })).toBeVisible()
  await tools(page, 'Customers'); await expect(page.locator('.tool-card').filter({ has: page.getByRole('heading', { name: 'Ana', exact: true }) })).toContainText('Loyalty points: 1.13'); await page.getByRole('button', { name: 'Purchase history' }).click(); await expect(page.getByRole('dialog')).toContainText('Returned ₱25.20'); await page.getByRole('button', { name: 'Close dialog' }).click()
  await tools(page, 'Analytics'); await expect(page.locator('.tool-stats')).toContainText('₱25.20'); await expect(page.getByText('Refunds: ₱25.20 · Net tax recorded: ₱2.70')).toBeVisible()
  await navigate(page, 'Sales history'); await page.getByRole('button', { name: 'Void / refund 1', exact: true }).click(); await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Remaining bottle returned'); await page.getByRole('button', { name: 'Record correction' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByText('Refunded', { exact: true })).toBeVisible()
  await tools(page, 'Customers'); await expect(page.locator('.tool-card').filter({ has: page.getByRole('heading', { name: 'Ana', exact: true }) })).toContainText('Loyalty points: 0.00')
})

test('supplier purchases, receiving, counts, and printable barcode labels work together', async ({ page }) => {
  const violations: string[] = []; page.on('console', message => { if (/Content Security Policy|Refused to/.test(message.text())) violations.push(message.text()) })
  await tools(page, 'Purchasing'); await page.getByRole('button', { name: 'Add supplier', exact: true }).click(); await page.getByLabel('Supplier name').fill('Wholesale shop'); await page.getByRole('button', { name: 'Save supplier' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'New purchase order', exact: true }).click(); const dialog = page.getByRole('dialog'); await dialog.getByRole('combobox', { name: 'Purchase product', exact: true }).selectOption({ label: 'Coca-Cola Original' }); await dialog.getByRole('button', { name: 'Add purchase item' }).click(); await dialog.getByRole('spinbutton', { name: 'Purchase quantity: Coca-Cola Original', exact: true }).fill('12'); await dialog.getByLabel('Unit cost: Coca-Cola Original').fill('15'); await dialog.getByRole('button', { name: 'Create purchase order' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await page.getByRole('button', { name: 'Receive purchase', exact: true }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0)
  await tools(page, 'Inventory'); await page.getByLabel('Find inventory products').fill('Coca-Cola'); await expect(page.locator('.tool-card').filter({ hasText: 'Coca-Cola Original' }).first()).toContainText('Stock: 12 · Cost: ₱15.00'); await page.getByRole('button', { name: 'Count selected stock' }).click(); await page.getByRole('spinbutton', { name: 'Count: Coca-Cola Original', exact: true }).fill('10'); await page.getByLabel('Count reason').fill('Physical count'); await page.getByRole('button', { name: 'Apply stock count' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.locator('.tool-card').filter({ hasText: 'Coca-Cola Original' }).first()).toContainText('Stock: 10')
  await page.getByRole('button', { name: 'Print barcode labels', exact: true }).click(); await expect(page.locator('.barcode-label svg rect').first()).toBeVisible(); await page.emulateMedia({ media: 'print' }); await expect(page.locator('.app-shell')).toBeHidden(); await expect(page.locator('.barcode-labels')).toBeVisible(); expect(violations).toEqual([]); await page.emulateMedia({ media: 'screen' }); await page.getByRole('button', { name: 'Close dialog' }).click()
})

test('saved orders can be split, combined, reopened, and completed', async ({ page }) => {
  await scan(page); await scan(page); await page.getByRole('button', { name: 'Save order', exact: true }).click(); await page.getByRole('textbox', { name: 'Order name', exact: true }).fill('Table 1'); await page.getByLabel('Saved order notes').fill('No bag'); await page.getByRole('dialog').getByRole('button', { name: 'Save order', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.locator('.cart-table tbody tr')).toHaveCount(0)
  await page.getByRole('button', { name: 'Saved orders', exact: true }).click(); await page.getByRole('button', { name: 'Split order', exact: true }).click(); await page.getByLabel('New split order name').fill('Table 2'); await page.getByLabel('Move quantity: Coca-Cola Original').fill('1'); await page.getByRole('button', { name: 'Save split order' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await page.getByRole('checkbox', { name: 'Select order Table 1', exact: true }).check(); await page.getByRole('checkbox', { name: 'Select order Table 2', exact: true }).check(); await page.getByRole('button', { name: 'Combine selected orders' }).click(); await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await page.getByRole('button', { name: 'Open order', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Sell', exact: true })).toBeVisible(); await expect(page.locator('.cart-table tbody tr')).toHaveCount(2); await page.getByRole('button', { name: 'Checkout', exact: true }).click(); await page.getByText('Customer, discounts, tax, and order details', { exact: true }).click(); await expect(page.getByRole('textbox', { name: 'Order notes', exact: true })).toHaveValue('No bag; No bag'); await page.getByRole('button', { name: 'Complete sale', exact: true }).click(); await expect(page.getByRole('dialog')).toContainText('₱50.00')
})

test('weighed products sell and return bags with correct kilogram stock', async ({ page }) => {
  await navigate(page, 'Products'); await productAction(page, 'Edit'); const dialog = page.getByRole('dialog'); await dialog.getByLabel('Sell by').selectOption('kg'); await dialog.getByLabel('Unit price (₱)').fill('80'); await dialog.getByRole('spinbutton', { name: 'Stock quantity (kg)', exact: true }).fill('2.5'); await dialog.getByLabel('Low-stock alert at (kg)').fill('.5'); await dialog.getByRole('button', { name: 'Save product', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(0)
  await navigate(page, 'Sell'); await scan(page); await page.getByLabel('Bag weight (kg)').fill('.25'); await page.getByRole('button', { name: 'Add with options' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await page.getByRole('button', { name: 'Increase Coca-Cola Original (0.25 kg) quantity' }).click(); await page.getByRole('button', { name: 'Checkout', exact: true }).click(); await expect(page.getByLabel('Amount received (₱)')).toHaveValue('40.00'); await page.getByRole('button', { name: 'Complete sale' }).click(); await page.getByRole('button', { name: 'Done', exact: true }).click(); await navigate(page, 'Products'); await expect(page.getByRole('row').filter({ hasText: 'Coca-Cola Original' })).toContainText('2 kg')
  await navigate(page, 'Sales history'); await page.getByRole('button', { name: 'Void / refund 1', exact: true }).click(); await page.getByRole('spinbutton', { name: 'Refund quantity: Coca-Cola Original (0.25 kg)', exact: true }).fill('1'); await page.getByRole('textbox', { name: 'Reason', exact: true }).fill('Returned one bag'); await page.getByRole('button', { name: 'Record correction' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await navigate(page, 'Products'); await expect(page.getByRole('row').filter({ hasText: 'Coca-Cola Original' })).toContainText('2.25 kg')
})

test('cash drawer records movements and closing discrepancies', async ({ page }) => {
  await tools(page, 'Cash drawer'); await page.getByLabel('Opening cash (₱)').fill('100'); await page.getByRole('button', { name: 'Open cash shift' }).click(); await expect(page.getByRole('heading', { name: 'Open shift #1' })).toBeVisible(); await page.getByRole('combobox', { name: 'Cash movement', exact: true }).selectOption('in'); await page.getByLabel('Cash amount (₱)').fill('20'); await page.getByLabel('Cash reason').fill('Float'); await page.getByRole('button', { name: 'Record cash movement' }).click(); await expect(page.locator('.checkout-total')).toContainText('₱120.00')
  await navigate(page, 'Sell'); await scan(page); await page.getByRole('button', { name: 'Checkout', exact: true }).click(); await page.getByRole('button', { name: 'Complete sale', exact: true }).click(); await page.getByRole('button', { name: 'Done', exact: true }).click(); await tools(page, 'Cash drawer'); await expect(page.locator('.checkout-total')).toContainText('₱145.00'); await page.getByRole('button', { name: 'Close cash shift' }).click(); await page.getByLabel('Counted cash (₱)').fill('144'); await page.getByRole('button', { name: 'Save closing cash count' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0); await expect(page.getByText('Difference: -₱1.00', { exact: true })).toBeVisible()
})

test('customer display updates in another window on the same device', async ({ page }) => {
  const popup = page.waitForEvent('popup'); await page.getByRole('link', { name: 'Customer display', exact: true }).click(); const display = await popup; await expect(display.getByRole('heading', { name: 'Thank you!' })).toBeVisible(); await scan(page); await expect(display.getByText('Coca-Cola Original × 1', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Checkout', exact: true }).click(); await page.getByRole('button', { name: 'Complete sale', exact: true }).click(); await expect(display.getByRole('heading', { name: 'Thank you!' })).toBeVisible(); await expect(display.getByText(/Latest receipt #1/)).toContainText('₱25.00'); await display.close()
})
test('employee PIN sign-in identifies sales and restricts cashier changes', async ({ page }) => {
  await navigate(page, 'Settings'); await page.getByLabel('New owner PIN (6–12 digits)').fill('987654'); await page.getByLabel('Confirm owner PIN').fill('987654'); await page.getByRole('button', { name: 'Save owner PIN' }).click(); await expect(page.getByRole('button', { name: 'Unlock owner access' })).toBeVisible(); await page.getByRole('textbox', { name: 'Owner PIN', exact: true }).fill('987654'); await page.getByRole('button', { name: 'Unlock owner access' }).click(); await expect(page.getByRole('button', { name: 'Lock owner access' })).toBeVisible()
  await tools(page, 'Employees'); await page.getByRole('button', { name: 'Add employee', exact: true }).click(); await page.getByRole('dialog').getByRole('textbox', { name: 'Employee name', exact: true }).fill('Ana'); await page.getByLabel('New employee PIN').fill('123456'); await page.getByRole('button', { name: 'Save employee' }).click(); await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Employee', exact: true }).selectOption({ label: 'Ana' }); await page.getByRole('textbox', { name: 'Employee PIN', exact: true }).fill('123456'); await page.getByRole('button', { name: 'Sign in employee', exact: true }).click(); await expect(page.getByText('Signed in: Ana', { exact: true })).toBeVisible()
  await page.getByLabel('Time clock employee').selectOption({ label: 'Ana' }); await page.getByLabel('Time clock PIN').fill('123456'); await page.getByRole('button', { name: 'Clock in / out' }).click(); await expect(page.getByText(/Clocked in/)).toBeVisible()
  await navigate(page, 'Sell'); await scan(page); await page.getByRole('button', { name: 'Checkout', exact: true }).click(); await expect(page.getByLabel('Operator name')).toHaveValue('Ana'); await expect(page.getByLabel('Operator name')).toHaveAttribute('readonly', ''); await page.getByRole('button', { name: 'Complete sale' }).click(); await expect(page.getByRole('dialog')).toContainText('Operator: Ana'); await page.getByRole('button', { name: 'Done', exact: true }).click()
  await navigate(page, 'Products'); await productAction(page, 'Edit'); await page.getByLabel('Unit price (₱)').fill('1'); await page.getByRole('button', { name: 'Save product', exact: true }).click(); await expect(page.getByRole('dialog').getByRole('alert')).toContainText('requires a manager'); await page.getByRole('button', { name: 'Cancel', exact: true }).click()
})

test('unsupported camera scanning gives a usable manual fallback', async ({ page }) => {
  await page.evaluate(() => Object.defineProperty(window, 'BarcodeDetector', { value: undefined, configurable: true })); await page.getByRole('button', { name: 'Scan with camera', exact: true }).click(); await expect(page.getByRole('dialog')).toContainText('Use a keyboard scanner or enter the barcode.'); await page.getByRole('button', { name: 'Close dialog' }).click(); await scan(page); await expect(page.locator('.cart-table')).toContainText('Coca-Cola Original')
})
test('camera detector adds one item and releases the camera after a match', async ({ page }) => {
  await page.addInitScript(() => {
    const state = window as unknown as { __cameraStops: number; BarcodeDetector: unknown }; state.__cameraStops = 0
    state.BarcodeDetector = class { static async getSupportedFormats() { return ['ean_13'] }; async detect() { return [{ rawValue: '4800016000013' }] } }
    Object.defineProperty(navigator.mediaDevices, 'getUserMedia', { value: async () => { const stream = new MediaStream(); Object.defineProperty(stream, 'getTracks', { value: () => [{ stop: () => state.__cameraStops++ }] }); return stream } })
    HTMLMediaElement.prototype.play = async () => {}
  })
  await page.reload(); await page.getByRole('button', { name: 'Scan with camera', exact: true }).click(); await expect(page.getByRole('spinbutton', { name: 'Coca-Cola Original quantity' })).toHaveValue('1'); await expect(page.getByRole('dialog')).toHaveCount(0); expect(await page.evaluate(() => (window as unknown as { __cameraStops: number }).__cameraStops)).toBeGreaterThanOrEqual(1)
})
test('dark theme persists with readable product cards', async ({ page }, testInfo) => {
  await tools(page, 'Checkout settings'); await page.getByLabel('Use dark theme').check(); await page.getByRole('button', { name: 'Save checkout settings' }).click(); await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark'); await page.reload(); await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark'); await navigate(page, 'Products'); await expect(page.getByRole('row').filter({ hasText: 'Coca-Cola Original' })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: `test-results/products-dark-${testInfo.project.name}.png`, fullPage: true })
})

for (const width of [320, 412]) test(`store tools stay readable without horizontal overflow at ${width}px`, async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile-chrome', 'Phone layout check'); await page.setViewportSize({ width, height: 850 }); await tools(page, 'Customers')
  for (const section of ['Customers', 'Saved orders', 'Inventory', 'Purchasing', 'Cash drawer', 'Employees', 'Analytics', 'Checkout settings']) { await page.getByLabel('Choose a store tool').selectOption(section); await expect(page.getByRole('heading', { name: section === 'Analytics' ? 'Sales analytics' : section, exact: true })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); const controls = await page.locator('.main-content input:not([type=checkbox]), .main-content select').evaluateAll(elements => elements.filter(element => element.getClientRects().length).map(element => { const rect = element.getBoundingClientRect(); return { size: parseFloat(getComputedStyle(element).fontSize), left: rect.left, right: rect.right } })); expect(controls.every(control => control.size >= 16 && control.left >= 0 && control.right <= width)).toBe(true) }
  await page.screenshot({ path: `test-results/store-tools-${width}.png`, fullPage: true })
})
