import { useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { checkout, db, money, type CartItem, type Payment, type Sale } from './db'
import { Field, Modal } from './components'
import { cartPricing } from './pricing'
import { type CheckoutOptions, type RetailSettings, type Ticket } from './retail-types'
import { runWork } from './work'
import { storageExportPrompt } from './storage'
import { staffSession } from './staff-access'

export function CheckoutDialog({ storageBlocked, onExport, cart, operator: initialOperator, config, context, onClose, onError, onComplete }: { storageBlocked: boolean; onExport: () => void; cart: CartItem[]; operator: string; config: RetailSettings; context: CheckoutOptions; onClose: () => void; onError: (error: unknown) => void; onComplete: (sale: Sale) => void }) {
  const [payment, setPayment] = useState<Payment>('cash'), [operator, setOperator] = useState(initialOperator), [busy, setBusy] = useState(false)
  const [discountType, setDiscountType] = useState(config.discountType), [discount, setDiscount] = useState((config.discountValue / 100).toFixed(2)), [taxRate, setTaxRate] = useState((config.taxRate / 100).toFixed(2)), [taxMode, setTaxMode] = useState(config.taxMode)
  const [customerId, setCustomerId] = useState(String(context.customerId ?? '')), [customerSearch, setCustomerSearch] = useState(''), [redeem, setRedeem] = useState('0'), [notes, setNotes] = useState(context.notes ?? ''), [dining, setDining] = useState<Ticket['dining']>(context.dining ?? 'retail')
  const [cashPart, setCashPart] = useState('0'), [otherPayment, setOtherPayment] = useState<'gcash' | 'card'>('gcash')
  const [ref, setRef] = useState(''), [splitRef, setSplitRef] = useState('')
  const showRef = payment !== 'cash' && payment !== 'split'
  const showSplitRef = payment === 'split'
  const customers = useLiveQuery(() => db.customers.orderBy('name').toArray(), [], [])
  const customer = customers.find(value => value.id === Number(customerId))
  const options: CheckoutOptions = { discountType, discountValue: Math.round(Number(discount) * 100), taxMode, taxRate: Math.round(Number(taxRate) * 100), ...(customerId ? { customerId: Number(customerId) } : {}), redeem: Math.round(Number(redeem) * 100), notes, dining }
  let pricing: ReturnType<typeof cartPricing> | undefined, pricingError = ''
  try { pricing = cartPricing(cart, options) } catch (error) { pricingError = error instanceof Error ? error.message : 'Check the checkout amounts.' }
  const total = pricing?.total ?? 0
  const [received, setReceived] = useState((total / 100).toFixed(2)), [receivedEdited, setReceivedEdited] = useState(false)
  const amountText = payment === 'cash' && receivedEdited ? received : (total / 100).toFixed(2), tendered = Math.round(Number(amountText) * 100), change = tendered - total
  const cash = Math.round(Number(cashPart) * 100), other = total - cash
  return <Modal title="Checkout" busy={busy} onClose={onClose}><>{storageBlocked && <div className="notice warning" role="alert"><p>{storageExportPrompt}</p><button className="button secondary" disabled={busy} onClick={onExport}>Export full backup</button></div>}<form data-edit-form onSubmit={async event => {
    event.preventDefault(); if (busy || storageBlocked) return
    if ([discount, taxRate, redeem, amountText, ...(payment === 'split' ? [cashPart] : [])].some(value => !/^\d+(\.\d{1,2})?$/.test(value))) { onError(new Error('Enter amounts and percentages with up to two decimal places.')); return }
    if (!pricing || pricingError) { onError(new Error(pricingError)); return }
    if (payment === 'split') options.payments = [{ method: 'cash', amount: cash }, { method: otherPayment, amount: other, ...(splitRef.trim() ? { ref: splitRef.trim() } : {}) }]
    else if (payment !== 'cash') options.payments = [{ method: payment, amount: total, ...(ref.trim() ? { ref: ref.trim() } : {}) }]
    setBusy(true)
    try { onComplete(await runWork(() => checkout(cart, payment, tendered, operator, options))) } catch (error) { onError(error) } finally { setBusy(false) }
  }}><div className="checkout-total"><span>Total · {cart.reduce((sum, row) => sum + row.quantity, 0)} items</span><strong>{money(total)}</strong></div>{pricing && (pricing.discount > 0 || pricing.tax > 0 || pricing.redeemed > 0) && <div className="receipt-totals"><p><span>Subtotal</span><strong>{money(pricing.subtotal)}</strong></p><p><span>Discounts</span><strong>−{money(pricing.discount)}</strong></p><p><span>Loyalty redemption</span><strong>−{money(pricing.redeemed)}</strong></p><p><span>Tax {taxMode === 'included' ? '(included)' : '(added)'}</span><strong>{money(pricing.tax)}</strong></p></div>}{pricingError && <p className="error-text" role="alert">{pricingError}</p>}
    <Field label="Payment method" required><select required value={payment} onChange={event => { setPayment(event.target.value as Payment); setReceivedEdited(false) }}><option value="cash">Cash</option><option value="gcash">GCash</option><option value="card">Card</option><option value="split">Split: cash + GCash / card</option></select></Field>{payment === 'split' && <><Field label="Cash part (₱)" required><input required type="number" inputMode="decimal" min="0.01" max={Math.max(0, total / 100 - .01)} step="0.01" value={cashPart} onChange={event => setCashPart(event.target.value)} /></Field><Field label="Other payment" required><select required value={otherPayment} onChange={event => setOtherPayment(event.target.value as 'gcash' | 'card')}><option value="gcash">GCash</option><option value="card">Card</option></select></Field><p className="form-note">{otherPayment === 'gcash' ? 'GCash' : 'Card'} part: {money(other)}. Enter the exact cash share; handle any change outside this split.</p></>}
    {(payment === 'gcash' || (payment === 'split' && otherPayment === 'gcash')) && config.gcashNumber && <p className="notice" role="status">Collect {money(payment === 'split' ? other : total)} to GCash {config.gcashName} · {config.gcashNumber}. Verify the payment in your GCash app before completing the sale.</p>}
    {showRef && <Field label="Reference number (optional)"><input maxLength={50} autoComplete="off" spellCheck={false} placeholder="GCash ref no. if needed" value={ref} onChange={event => setRef(event.target.value)} /></Field>}
    {showSplitRef && <Field label="Reference number (optional)"><input maxLength={50} autoComplete="off" spellCheck={false} placeholder="GCash ref no. if needed" value={splitRef} onChange={event => setSplitRef(event.target.value)} /></Field>}
    <Field label="Amount received (₱)" required><input data-autofocus type="number" inputMode="decimal" required min={total / 100} max="999999999.99" step="0.01" value={amountText} readOnly={payment !== 'cash'} onChange={event => { setReceived(event.target.value); setReceivedEdited(true) }} /></Field><p className={change < 0 ? 'error-text' : 'change-value'}>{change < 0 ? 'The amount received is below the total.' : `Change: ${money(change)}`}</p>
    <Field label="Operator name" required><input required maxLength={100} readOnly={!!staffSession()} value={operator} onChange={event => setOperator(event.target.value)} /></Field>
    <details className="product-extras"><summary>Customer, discounts, tax, and order details</summary><Field label="Find checkout customer"><input placeholder="Name, phone or loyalty card" value={customerSearch} onChange={event => { const value = event.target.value; setCustomerSearch(value); const match = customers.find(customer => customer.card && customer.card === value.trim()); if (match) { setCustomerId(String(match.id)); setRedeem('0') } }} /></Field><Field label="Customer"><select value={customerId} onChange={event => { setCustomerId(event.target.value); setRedeem('0') }}><option value="">Walk-in customer</option>{customers.filter(value => value.id === Number(customerId) || `${value.name} ${value.phone} ${value.card}`.toLowerCase().includes(customerSearch.toLowerCase())).slice(0, 100).map(value => <option value={value.id} key={value.id}>{value.name}</option>)}</select></Field>{customer && <><p className="form-note">Available loyalty points: {(customer.balance / 100).toFixed(2)} · 1 point = ₱1</p><Field label="Redeem loyalty points" required><input required type="number" min="0" max={Math.max(0, customer.balance / 100)} step="0.01" value={redeem} onChange={event => setRedeem(event.target.value)} /></Field></>}
      <div className="form-grid"><Field label="Order discount type" required><select value={discountType} onChange={event => { setDiscountType(event.target.value as 'amount' | 'percent'); setDiscount('0') }}><option value="amount">Amount (₱)</option><option value="percent">Percentage (%)</option></select></Field><Field label="Order discount value" required><input required type="number" min="0" max={discountType === 'percent' ? 100 : undefined} step="0.01" value={discount} onChange={event => setDiscount(event.target.value)} /></Field></div><Field label="Checkout tax mode" required><select value={taxMode} onChange={event => setTaxMode(event.target.value as RetailSettings['taxMode'])}><option value="none">No tax calculation</option><option value="included">Included in prices</option><option value="added">Added to total</option></select></Field><Field label="Checkout tax rate (%)" required><input required type="number" min="0" max="100" step="0.01" value={taxRate} onChange={event => setTaxRate(event.target.value)} /></Field><Field label="Order type" required><select value={dining} onChange={event => setDining(event.target.value as Ticket['dining'])}><option value="retail">Retail</option><option value="dine-in">Dine in</option><option value="takeaway">Takeaway</option><option value="delivery">Delivery</option></select></Field><Field label="Order notes"><textarea rows={2} maxLength={200} value={notes} onChange={event => setNotes(event.target.value)} /></Field>
    </details><div className="actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || storageBlocked || change < 0 || !!pricingError || (payment === 'split' && (cash <= 0 || other <= 0))}>{busy ? 'Saving sale…' : 'Complete sale'}</button></div></form></></Modal>
}
