import { useEffect, useRef, useState, useSyncExternalStore } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { ArrowDown, ArrowUp, ChevronsUpDown, Download, Pencil, Plus, Trash2 } from 'lucide-react'
import { adjustStock, categories, correctSale, db, deleteProduct, exportDatabase, getHistorySummaries, getReport, money, requireOwner, resetDatabase, restoreDatabase, setOwnerCredential, setPreferences, today, type Preferences, type Product, type Report, type Sale } from './db'
import { Field, Modal, csv } from './components'
import { lowStockAt, stockFactor, stockText } from './pricing'
import { readBackupFile } from './backup'
import { encodeBackup, serializeBackup } from './backup-format'
import { catalogCSV, importCatalog, parseCatalog } from './catalog'
import { createOwnerCredential, lockOwner, ownerSnapshot, subscribeOwner, unlockOwner, type OwnerCredential } from './owner'
import { runWork, setFormDirty } from './work'
import type { ValidatedBackup } from './validation'

interface Feedback { onError: (error: unknown) => void; notify: (message: string, error?: boolean) => void }
export function downloadText(contents: string, name: string, type = 'application/json') {
  const url = URL.createObjectURL(new Blob([contents], { type }))
  const link = document.createElement('a')
  link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove()
  setTimeout(() => URL.revokeObjectURL(url), 30_000)
}
export function ProductsView({ products, onAdd, onEdit, onError, notify }: Feedback & { products: Product[]; onAdd: () => void; onEdit: (product: Product) => void }) {
  const [search, setSearch] = useState(''), [category, setCategory] = useState('All products')
  const [deleting, setDeleting] = useState<Product | null>(null), [stockProduct, setStockProduct] = useState<Product | null>(null)
  const [managedProduct, setManagedProduct] = useState<Product | null>(null)
  const [preview, setPreview] = useState<Product[] | null>(null), [busy, setBusy] = useState(false)
  const file = useRef<HTMLInputElement>(null)
  const filtered = products.filter(product => (category === 'All products' || product.category === category) && `${product.name} ${product.barcode}`.toLowerCase().includes(search.toLowerCase()))
  const [sortKey, setSortKey] = useState<'name' | 'price' | 'stock' | null>(null), [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc')
  const sorted = sortKey ? [...filtered].sort((a, b) => {
    if (sortKey === 'price') return (sortDir === 'asc' ? 1 : -1) * (a.price - b.price) || a.name.localeCompare(b.name)
    if (sortKey === 'stock') {
      if (a.stock === undefined && b.stock === undefined) return a.name.localeCompare(b.name)
      if (a.stock === undefined) return 1
      if (b.stock === undefined) return -1
      return (sortDir === 'asc' ? 1 : -1) * (a.stock - b.stock) || a.name.localeCompare(b.name)
    }
    return (sortDir === 'asc' ? 1 : -1) * a.name.localeCompare(b.name) || a.barcode.localeCompare(b.barcode)
  }) : filtered
  function toggleSort(key: 'name' | 'price' | 'stock') {
    if (sortKey === key) setSortDir(dir => dir === 'asc' ? 'desc' : 'asc')
    else { setSortKey(key); setSortDir('asc') }
  }
  function sortButton(key: 'name' | 'price' | 'stock', label: string) {
    const active = sortKey === key, state = active ? (sortDir === 'asc' ? 'sorted ascending, activate for descending order' : 'sorted descending, activate for ascending order') : 'not sorted, activate for ascending order'
    return <button type="button" className="th-sort" aria-label={`Sort by ${label.toLowerCase()}: ${state}`} onClick={() => toggleSort(key)}><span>{label}</span>{active ? (sortDir === 'asc' ? <ArrowUp size={16} aria-hidden="true" /> : <ArrowDown size={16} aria-hidden="true" />) : <ChevronsUpDown size={16} aria-hidden="true" className="sort-idle" />}</button>
  }
  function sortState(key: 'name' | 'price' | 'stock'): 'ascending' | 'descending' | 'none' {
    return sortKey === key ? (sortDir === 'asc' ? 'ascending' : 'descending') : 'none'
  }
  const [page, setPage] = useState(1)
  useEffect(() => setPage(1), [search, category, sortKey, sortDir])
  const pages = Math.max(1, Math.ceil(filtered.length / 50)), currentPage = Math.min(page, pages)
  const low = products.filter(product => product.stock !== undefined && product.stock <= lowStockAt(product))
  async function act(action: () => Promise<void>) { if (busy) return; setBusy(true); try { await runWork(action) } catch (error) { onError(error) } finally { setBusy(false) } }
  return <>
    <div className="page-heading products-heading"><div><h1>Products</h1><p>Manage prices, barcodes, and stock.</p></div><button className="button primary" onClick={onAdd}><Plus size={18} />Add product</button></div>
    {!!low.length && <p className="notice warning">{low.length} {low.length === 1 ? 'product is' : 'products are'} low on stock: {low.slice(0, 5).map(product => product.name).join(',')}{low.length > 5 ? '…' : ''}</p>}
    <section className="panel products-panel"><div className="toolbar products-toolbar"><Field label="Search products"><input aria-label="Search products" placeholder="Name or barcode" value={search} onChange={event => setSearch(event.target.value)} /></Field><Field label="Category" className="filter-field full-filter"><select aria-label="Product category" value={category} onChange={event => setCategory(event.target.value)}>{['All products', ...categories].map(item => <option key={item}>{item}</option>)}</select></Field><button type="button" className="button secondary" onClick={() => void act(async () => { await requireOwner(); downloadText(catalogCSV(products), `Tindahan-products-${today()}.csv`, 'text/csv;charset=utf-8'); notify('Catalog CSV exported.') })}>Export CSV</button><button type="button" className="button secondary" disabled={busy} onClick={() => file.current?.click()}>Import CSV</button><input className="sr-only" ref={file} type="file" accept=".csv,text/csv" aria-label="Choose catalog CSV" onChange={event => {
      const selected = event.target.files?.[0]; event.target.value = ''
      if (selected) void act(async () => { await requireOwner(); if (selected.size > 2 * 1024 * 1024) throw new Error('Choose a CSV smaller than 2 MB.'); setPreview(parseCatalog(await selected.text())) })
    }} /></div>
    <div className="table-scroll products-list"><table className="mobile-records product-records"><thead><tr><th scope="col" aria-sort={sortState('name')}>{sortButton('name', 'Product')}</th><th scope="col" aria-sort={sortState('price')}>{sortButton('price', 'Unit price')}</th><th scope="col" aria-sort={sortState('stock')}>{sortButton('stock', 'Stock')}</th><th scope="col">Actions</th></tr></thead><tbody>{sorted.slice((currentPage - 1) * 50, currentPage * 50).map(product => <tr key={product.id}><td className="record-title"><strong>{product.name}</strong><small className="product-meta"><span className="product-barcode">{product.barcode}</span><span className="product-category">{product.category}</span>{product.variant && <span>{product.variant}</span>}</small></td><td className="numeric" data-label="Unit price">{money(product.price)}{product.unit === 'kg' && <small>per kg</small>}</td><td data-label="Stock">{product.stock === undefined ? <span className="muted">Not tracked</span> : <span className={product.stock <= lowStockAt(product) ? 'stock-low' : ''}>{stockText(product)}{product.stock <= lowStockAt(product) ? ' · Low' : ''}</span>}</td><td className="record-actions"><div className="row-actions desktop-product-actions"><button className="icon-button" aria-label={`Edit ${product.name}`} onClick={() => onEdit(product)}><Pencil size={18} /></button><button className="button small secondary" onClick={() => setStockProduct(product)}>Adjust stock<span className="sr-only"> for {product.name}</span></button><button className="icon-button danger-text" aria-label={`Delete ${product.name}`} onClick={() => setDeleting(product)}><Trash2 size={18} /></button></div><button className="button secondary mobile-product-manage" aria-label={`Manage ${product.name}`} onClick={() => setManagedProduct(product)}>Manage product</button></td></tr>)}</tbody></table></div>
    {!filtered.length && <div className="empty-state">{products.length ? 'No matching products.' : 'No products yet. Add a product or import a CSV.'}</div>}
    <Pagination page={currentPage} pages={pages} setPage={setPage} /><p className="panel-foot">{filtered.length} products. Starter barcodes and prices are examples; check them before selling.</p></section>
    {managedProduct && <Modal title="Manage product" onClose={() => setManagedProduct(null)}><p><strong>{managedProduct.name}</strong></p><p className="form-note">{managedProduct.barcode} · {money(managedProduct.price)}</p><div className="product-management-actions"><button className="button secondary" aria-label={`Edit ${managedProduct.name}`} onClick={() => { const product = managedProduct; setManagedProduct(null); onEdit(product) }}>Edit product</button><button className="button secondary" aria-label={`Adjust stock for ${managedProduct.name}`} onClick={() => { setStockProduct(managedProduct); setManagedProduct(null) }}>Adjust stock</button><button className="button secondary danger-text" aria-label={`Delete ${managedProduct.name}`} onClick={() => { setDeleting(managedProduct); setManagedProduct(null) }}>Delete product</button></div></Modal>}
    {deleting && <Modal title="Delete product?" busy={busy} onClose={() => setDeleting(null)}><p>Delete {deleting.name} from the catalog? Existing sales keep their original details.</p><div className="actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(null)}>Cancel</button><button className="button danger" disabled={busy} onClick={() => void act(async () => { await deleteProduct(deleting.id!); setDeleting(null); notify('Product deleted.') })}>Delete product</button></div></Modal>}
    {stockProduct && <Modal title={`Adjust stock: ${stockProduct.name}`} busy={busy} onClose={() => { setStockProduct(null); setFormDirty(false) }}><form data-edit-form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void act(async () => { await adjustStock(stockProduct.id!, Math.round(Number(data.get('stock')) * stockFactor(stockProduct)), String(data.get('reason'))); setStockProduct(null); setFormDirty(false); notify('Stock updated. The adjustment was recorded.') }) }}><Field label={stockProduct.unit === 'kg' ? 'New stock quantity (kg)' : 'New stock quantity'} required><input data-autofocus name="stock" type="number" min="0" max="1000000000" step={stockProduct.unit === 'kg' ? '.001' : '1'} required placeholder={stockProduct.stock === undefined ? 'e.g. 24' : `Current: ${stockText(stockProduct)}`} /></Field><Field label="Reason"><textarea name="reason" maxLength={200} rows={2} placeholder="e.g. Restocked" aria-describedby="stock-reason-hint" /></Field><p id="stock-reason-hint" className="form-note">Optional: describe the stock change, such as a delivery or damaged goods.</p><div className="actions"><button className="button primary" disabled={busy}>Save stock adjustment</button></div></form></Modal>}
    {preview && <Modal title="Review catalog import" wide busy={busy} onClose={() => setPreview(null)}><p>{preview.length} products will be added or updated by barcode. Prices and stock in the CSV replace catalog values. Empty stock fields turn tracking off.</p><p className="form-note">{preview.filter(product => products.some(current => current.barcode === product.barcode)).length} existing barcodes will be updated. Existing sales keep their original prices.</p><div className="table-scroll"><table className="mobile-records"><thead><tr><th>Product</th><th>Barcode</th><th>Price</th><th>Stock</th></tr></thead><tbody>{preview.slice(0, 20).map(product => <tr key={product.barcode}><td className="record-title">{product.name}</td><td data-label="Barcode">{product.barcode}</td><td data-label="Unit price">{money(product.price)}{product.unit === 'kg' && <small>per kg</small>}</td><td data-label="Stock">{product.stock ?? 'Not tracked'}</td></tr>)}</tbody></table></div>{preview.length > 20 && <p>Showing the first 20 products.</p>}<div className="actions"><button className="button secondary" disabled={busy} onClick={() => setPreview(null)}>Cancel</button><button className="button primary" disabled={busy} onClick={() => void act(async () => { await importCatalog(preview); setPreview(null); notify('Catalog imported.') })}>Import {preview.length} products</button></div></Modal>}
  </>
}
export function Pagination({ page, pages, setPage }: { page: number; pages: number; setPage: (page: number) => void }) {
  return pages > 1 ? <nav className="pagination" aria-label="Pages"><button className="button small secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous page</button><span>Page {page} of {pages}</span><button className="button small secondary" disabled={page === pages} onClick={() => setPage(page + 1)}>Next page</button></nav> : null
}
export function HistoryView({ onView, onDownload, onCloseDay, onError }: { onView: (report: Report) => void; onDownload: (report: Report) => Promise<void>; onCloseDay: (id: number) => Promise<void>; onError: (error: unknown) => void }) {
  const records = useLiveQuery(getHistorySummaries, [], [])
  const [search, setSearch] = useState(''), [date, setDate] = useState(''), [filter, setFilter] = useState('All reports'), [page, setPage] = useState(1)
  const visible = records.filter(record => record.searchText.includes(search.toLowerCase()) && (!date || record.session.date === date) && (filter === 'All reports' || (filter === 'Closed' ? record.session.status === 'closed' : record.session.status === 'open')))
  const pages = Math.max(1, Math.ceil(visible.length / 20)), currentPage = Math.min(page, pages)
  useEffect(() => setPage(1), [search, date, filter])
  async function open(id: number, download = false) { try { await runWork(async () => { const report = await getReport(id); if (download) await onDownload(report); else onView(report) }) } catch (error) { onError(error) } }
  return <><div className="page-heading"><div><h1>Daily reports</h1><p>Completed sales, refunds, and closed days.</p></div></div><section className="panel"><div className="toolbar"><Field label="Search reports"><input aria-label="Search reports" placeholder="Store or date" value={search} onChange={event => setSearch(event.target.value)} /></Field><Field label="Date"><input type="date" aria-label="Filter reports by date" value={date} onChange={event => setDate(event.target.value)} /></Field><Field label="Status" className="filter-field"><select aria-label="Report status" value={filter} onChange={event => setFilter(event.target.value)}>{['All reports', 'Closed', 'Open days'].map(item => <option key={item}>{item}</option>)}</select></Field></div><div className="table-scroll"><table className="mobile-records"><thead><tr><th>Date / store</th><th>Status</th><th>Items sold</th><th>Net sales</th><th>Report</th></tr></thead><tbody>{visible.slice((currentPage - 1) * 20, currentPage * 20).map(record => <tr key={record.session.id}><td className="record-title"><strong>{record.dateText}</strong><small>{record.session.storeName || 'My store'} · #{record.session.id}</small></td><td data-label="Status">{record.session.status === 'closed' ? 'Closed' : 'Open'}</td><td data-label="Items sold">{record.items}</td><td className="numeric" data-label="Net sales">{money(record.value)}</td><td className="record-actions"><div className="row-actions"><button className="button small secondary" onClick={() => void open(record.session.id!)}>View</button><button className="icon-button" aria-label={`Download report ${record.session.id}`} onClick={() => void open(record.session.id!, true)}><Download size={18} /></button>{record.session.status === 'open' && <button className="button small secondary" onClick={() => void onCloseDay(record.session.id!)}>Close day</button>}</div></td></tr>)}</tbody></table></div>{!visible.length && <div className="empty-state">{records.length ? 'No reports match these filters.' : 'No sales reports yet. Complete your first checkout to start a report.'}</div>}<Pagination page={currentPage} pages={pages} setPage={setPage} /><p className="panel-foot">Refunds appear on the day they are recorded. Earlier closed reports retain their original totals.</p></section></>
}
export function SalesView({ onReceipt, onError, notify }: Feedback & { onReceipt: (sale: Sale) => void }) {
  const sales = useLiveQuery(() => db.sales.orderBy('createdAt').reverse().toArray(), [], [])
  const [search, setSearch] = useState(''), [page, setPage] = useState(1)
  const [correcting, setCorrecting] = useState<Sale | null>(null), [busy, setBusy] = useState(false)
  const visible = sales.filter(sale => `${sale.id} ${sale.operator} ${sale.storeName} ${sale.createdAt} ${sale.status}`.toLowerCase().includes(search.toLowerCase()))
  const pages = Math.max(1, Math.ceil(visible.length / 20)), currentPage = Math.min(page, pages)
  useEffect(() => setPage(1), [search])
  return <><div className="page-heading"><div><h1>Sales history</h1><p>View receipts and record item refunds or full-sale voids.</p></div></div><section className="panel"><div className="toolbar"><Field label="Search sales"><input aria-label="Search sales" value={search} onChange={event => setSearch(event.target.value)} placeholder="Receipt, operator or date" /></Field></div><div className="table-scroll"><table className="mobile-records"><thead><tr><th>Receipt</th><th>Operator / payment</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.slice((currentPage - 1) * 20, currentPage * 20).map(sale => <tr key={sale.id}><td className="record-title"><strong>#{String(sale.id).padStart(6, '0')}</strong><small>{new Date(sale.createdAt).toLocaleString('en-PH', { timeZone: 'Asia/Manila' })}</small></td><td data-label="Operator / payment">{sale.operator}<small>{sale.payment === 'gcash' ? 'GCash' : sale.payment === 'cash' ? 'Cash' : sale.payment === 'split' ? 'Split payment' : 'Card'}</small></td><td className="numeric" data-label="Total">{money(sale.total)}</td><td data-label="Status">{sale.status === 'completed' ? sale.refundedAmount ? 'Partly refunded' : 'Completed' : sale.status === 'voided' ? 'Voided' : 'Refunded'}</td><td className="record-actions"><div className="row-actions"><button className="button small secondary" onClick={() => onReceipt(sale)}>Receipt<span className="sr-only"> {sale.id}</span></button><button className="button small secondary" disabled={sale.status !== 'completed'} onClick={() => setCorrecting(sale)}>Void / refund<span className="sr-only"> {sale.id}</span></button></div></td></tr>)}</tbody></table></div>{!visible.length && <div className="empty-state">No completed sales match this search.</div>}<Pagination page={currentPage} pages={pages} setPage={setPage} /></section>
    {correcting && <Modal title={`Correct sale #${correcting.id}`} busy={busy} onClose={() => { setCorrecting(null); setFormDirty(false) }}><p>The original sale stays in history. Refund selected items or void the entire sale. Corrections appear against today's sales.</p><form data-edit-form onSubmit={async event => {
      event.preventDefault(); if (busy) return; const data = new FormData(event.currentTarget); setBusy(true)
      try { await runWork(async () => { const action = data.get('action') as 'void' | 'refund', rows = await db.scans.where('saleId').equals(correcting.id!).toArray(); await correctSale(correcting.id!, action, String(data.get('reason')), data.get('stock') === 'on', action === 'refund' ? rows.map(row => ({ scanId: row.id!, quantity: Number(data.get(`refund-${row.id}`)) })) : undefined) }); setCorrecting(null); setFormDirty(false); notify('Correction recorded.') } catch (error) { onError(error) } finally { setBusy(false) }
    }}><Field label="Correction type" required><select name="action" required><option value="refund">Refund</option><option value="void">Void (current open day only)</option></select></Field><RefundItems sale={correcting} /><Field label="Reason" required><textarea data-autofocus name="reason" required maxLength={200} rows={2} placeholder="Reason for correction" /></Field><label className="check-field"><input name="stock" type="checkbox" defaultChecked />Return items to stock</label><p className="form-note">Keep this unchecked for damaged goods or items not returned.</p><div className="actions"><button className="button danger" disabled={busy}>Record correction</button></div></form></Modal>}
  </>
}
function RefundItems({ sale }: { sale: Sale }) {
  const data = useLiveQuery(async () => ({ rows: await db.scans.where('saleId').equals(sale.id!).toArray(), corrections: await db.corrections.where('saleId').equals(sale.id!).toArray() }), [sale.id])
  return <><p className="form-note">For a refund, enter the number of each item returned. Use zero to keep an item. A void always reverses the entire sale.</p>{data ? data.rows.map(row => { const returned = data.corrections.reduce((sum, correction) => sum + (correction.lines?.find(line => line.scanId === row.id)?.quantity ?? (correction.lines ? 0 : row.quantity)), 0), remaining = row.quantity - returned; return <Field key={row.id} label={`Refund quantity: ${row.name}`} required><input name={`refund-${row.id}`} required type="number" min="0" max={remaining} step="1" defaultValue={remaining} /></Field> }) : <p>Loading receipt items…</p>}</>
}
export function SettingsView({ prefs, onError, notify, onInstall, offlineReady }: Feedback & { prefs: Preferences; onInstall: () => void; offlineReady: boolean }) {
  const [storeName, setStoreName] = useState(prefs.storeName), [operator, setOperator] = useState(prefs.operator || 'Owner')
  const [scanPrefs, setScanPrefs] = useState({ increment: prefs.increment, sound: prefs.sound, paper: prefs.paper })
  const [busy, setBusy] = useState(false), [persisted, setPersisted] = useState(false), [usage, setUsage] = useState<StorageEstimate | null>(null)
  const credential = useLiveQuery(async () => (await db.settings.get('owner'))?.value as OwnerCredential | undefined)
  const lastExport = useLiveQuery(async () => (await db.settings.get('lastExport'))?.value as string | undefined)
  const unlocked = useSyncExternalStore(subscribeOwner, ownerSnapshot)
  const [action, setAction] = useState<'export' | 'restore' | 'reset' | 'removePin' | null>(null)
  const [backup, setBackup] = useState<ValidatedBackup | null>(null), [confirm, setConfirm] = useState('')
  const [encrypted, setEncrypted] = useState(false), [password, setPassword] = useState(''), [passwordConfirm, setPasswordConfirm] = useState('')
  const [pin, setPin] = useState(''), [pinConfirm, setPinConfirm] = useState(''), [unlockPin, setUnlockPin] = useState('')
  const [backupFile, setBackupFile] = useState<File | null>(null)
  const [backupSize, setBackupSize] = useState<number | null>(null)
  const activity = useLiveQuery(() => db.audit.orderBy('id').reverse().limit(50).toArray(), [], [])
  const abort = useRef<AbortController | null>(null)
  useEffect(() => { setStoreName(prefs.storeName); setOperator(prefs.operator || 'Owner') }, [prefs.storeName, prefs.operator])
  useEffect(() => { setScanPrefs({ increment: prefs.increment, sound: prefs.sound, paper: prefs.paper }) }, [prefs.increment, prefs.sound, prefs.paper])
  useEffect(() => { void navigator.storage?.persisted?.().then(setPersisted); void navigator.storage?.estimate?.().then(setUsage).catch(() => {}); return () => abort.current?.abort() }, [])
  async function act(operation: () => Promise<void>) { if (busy) return; setBusy(true); try { await runWork(operation) } catch (error) { onError(error) } finally { setBusy(false) } }
  function changeScanPrefs(changes: Partial<typeof scanPrefs>) {
    const previous = scanPrefs
    setScanPrefs({ ...scanPrefs, ...changes })
    void act(async () => { try { await setPreferences(changes) } catch (error) { setScanPrefs(previous); throw error } })
  }
  function close() { abort.current?.abort(); setAction(null); setBackup(null); setBackupFile(null); setConfirm(''); setPassword(''); setPasswordConfirm(''); setFormDirty(false) }
  const canAdmin = !credential || credential.hash === unlocked
  return <><div className="page-heading"><div><h1>Settings</h1><p>Store details, backups, and owner access.</p></div></div><div className="settings-grid">
    <section className="panel padded"><h2>Store details</h2><form data-edit-form onSubmit={event => { event.preventDefault(); void act(async () => { await setPreferences({ storeName: storeName.trim(), operator: operator.trim() }); setFormDirty(false); notify('Store details saved.') }) }}><Field label="Store name" required><input required maxLength={100} value={storeName} onChange={event => setStoreName(event.target.value)} /></Field><Field label="Operator name" required><input required maxLength={100} value={operator} onChange={event => setOperator(event.target.value)} /></Field><p className="form-note">The store name stays saved after closing a day. Operator names identify sales and adjustments; they are entered by the person using the app.</p><button className="button primary" disabled={busy}>Save store details</button></form><h3>Scanning and reports</h3><label className="check-field"><input type="checkbox" disabled={busy} checked={scanPrefs.increment} onChange={event => changeScanPrefs({ increment: event.target.checked })} />Group repeat scans</label><label className="check-field"><input type="checkbox" disabled={busy} checked={scanPrefs.sound} onChange={event => changeScanPrefs({ sound: event.target.checked })} />Play a sound after scanning</label><Field label="Report paper size"><select disabled={busy} value={scanPrefs.paper} onChange={event => changeScanPrefs({ paper: event.target.value as 'a4' | 'letter' })}><option value="a4">A4</option><option value="letter">Letter</option></select></Field></section>
    <section className="panel padded"><h2>Backups and storage</h2><p>Your records are stored in this browser. Keep a backup on another device or drive.</p><p className={lastExport ? 'form-note' : 'notice warning'}>{lastExport ? `Last export: ${new Date(lastExport).toLocaleString()}. Check that the file was saved.` : 'No backup has been exported from this device.'}</p><div className="stack-actions"><button className="button secondary" disabled={busy} onClick={() => { setAction('export'); setEncrypted(false) }}>Export full backup</button><button className="button secondary" disabled={busy} onClick={() => setAction('restore')}>Restore backup</button><button className="button secondary" disabled={busy} onClick={() => void act(async () => { await requireOwner(); const json = serializeBackup(await exportDatabase()); setBackupSize(new Blob([json]).size); notify('Backup checked. It fits the restore limits.') })}>Check backup size</button></div>{backupSize !== null && <p className="form-note">Full backup: {(backupSize / 1024 / 1024).toFixed(2)} MB of the 25 MB limit.</p>}<p className="form-note">{usage ? `Browser storage: ${((usage.usage ?? 0) / 1024 / 1024).toFixed(1)} MB used. Approximate quota: ${((usage.quota ?? 0) / 1024 / 1024).toFixed(0)} MB.` : 'Storage estimate is unavailable in this browser.'}</p><p className="form-note">{persisted ? 'Persistent storage is enabled. You still need backups.' : 'Persistent storage has not been enabled.'}</p><button className="button secondary" disabled={persisted || busy} onClick={() => void act(async () => { if (!navigator.storage?.persist) throw new Error('This browser does not support persistent storage. Keep exporting backups.'); const result = await navigator.storage.persist(); setPersisted(result); notify(result ? 'Persistent storage enabled.' : 'The browser declined persistent storage. Keep exporting backups.') })}>{persisted ? 'Persistence enabled' : 'Enable persistence'}</button><p className="form-note">{offlineReady ? 'Offline app files are ready.' : 'Wait for offline setup before using airplane mode.'}</p><button className="button secondary" onClick={onInstall}>Install app</button></section>
    <section className="panel padded"><h2>Owner access</h2><p>{credential ? canAdmin ? 'Owner access is unlocked for up to 15 minutes.' : 'Owner access is locked. Cashiers can still scan and check out.' : 'Set a PIN to restrict product edits, stock changes, corrections, and backup administration.'}</p>{credential && !canAdmin && <form data-edit-form onSubmit={event => { event.preventDefault(); void act(async () => { await unlockOwner(unlockPin, credential); setUnlockPin(''); setFormDirty(false); notify('Owner access unlocked.') }) }}><Field label="Owner PIN" required><input required type="password" inputMode="numeric" autoComplete="off" value={unlockPin} onChange={event => setUnlockPin(event.target.value)} minLength={6} maxLength={12} /></Field><button className="button primary" disabled={busy}>Unlock owner access</button></form>}{canAdmin && <form data-edit-form onSubmit={event => { event.preventDefault(); void act(async () => { if (pin !== pinConfirm) throw new Error('The PINs do not match.'); await setOwnerCredential(await createOwnerCredential(pin)); setPin(''); setPinConfirm(''); setFormDirty(false); notify('Owner PIN saved. Unlock owner access to make protected changes.') }) }}><Field label={credential ? 'New owner PIN' : 'New owner PIN (6–12 digits)'} required><input required type="password" pattern="[0-9]{6,12}" autoComplete="new-password" inputMode="numeric" value={pin} onChange={event => setPin(event.target.value)} /></Field><Field label="Confirm owner PIN" required><input required type="password" pattern="[0-9]{6,12}" autoComplete="new-password" inputMode="numeric" value={pinConfirm} onChange={event => setPinConfirm(event.target.value)} /></Field><button className="button primary" disabled={busy}>Save owner PIN</button></form>}{credential && canAdmin && <div className="stack-actions"><button className="button secondary" onClick={() => { lockOwner(); setFormDirty(false) }}>Lock owner access</button><button className="button secondary" onClick={() => setAction('removePin')}>Remove owner PIN</button></div>}<p className="form-note">The PIN limits access within the app. It does not encrypt local records or prevent access through the browser profile. Keep the device locked when unattended. A forgotten PIN cannot be recovered in the app.</p></section>
    <section className="panel padded"><h2>Recent activity</h2>{canAdmin ? <><p className="form-note">Latest 50 sales and administrative changes.</p><div className="tool-actions"><button type="button" className="button secondary" disabled={busy} onClick={() => void act(async () => { const rows = await db.audit.orderBy('id').toArray(); downloadText(csv([['Entry', 'Date', 'Action', 'Details', 'Operator'], ...rows.map(entry => [entry.id!, entry.createdAt, entry.action, entry.detail, entry.operator])]), `Tindahan-activity-${today()}.csv`, 'text/csv;charset=utf-8'); notify('Activity exported.') })}>Export activity CSV</button></div><ul className="activity-list">{activity.map(entry => <li key={entry.id}><strong>{entry.detail}</strong><small>{entry.operator} · {new Date(entry.createdAt).toLocaleString()}</small></li>)}</ul>{!activity.length && <p>No activity recorded yet.</p>}</> : <p>Unlock owner access to view activity.</p>}</section>
    <section className="panel padded danger-panel"><h2>Reset device data</h2><p>This permanently removes products, sales, carts, reports, and settings.</p><button className="button danger" disabled={busy} onClick={() => setAction('reset')}>Reset local data</button></section>
  </div>
  {action && <Modal title={action === 'export' ? 'Export full backup' : action === 'restore' ? 'Restore backup' : action === 'removePin' ? 'Remove owner PIN?' : 'Reset all device data?'} busy={busy} onClose={close}>
    {action === 'export' && <form data-edit-form onSubmit={event => { event.preventDefault(); void act(async () => {
      await requireOwner()
      if (encrypted && password !== passwordConfirm) throw new Error('The passwords do not match.')
      const json = await encodeBackup(await exportDatabase(), encrypted ? password : '')
      downloadText(json, `Tindahan-backup-${today()}-${Date.now()}${encrypted ? '.encrypted' : ''}.json`)
      await db.settings.put({ key: 'lastExport', value: new Date().toISOString() })
      close(); notify('Backup export started. Check your downloads and keep a copy off this device.')
    }) }}><p>Products, sales, cart, activity, and owner settings are included. Export is checked against restore limits before downloading.</p><label className="check-field"><input type="checkbox" checked={encrypted} onChange={event => setEncrypted(event.target.checked)} />Encrypt with a password</label>{encrypted && <><Field label="Backup password (at least 12 characters)" required><input type="password" required minLength={12} maxLength={200} autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} /></Field><Field label="Confirm backup password" required><input type="password" required minLength={12} maxLength={200} autoComplete="new-password" value={passwordConfirm} onChange={event => setPasswordConfirm(event.target.value)} /></Field><p className="form-note">Keep this password somewhere safe. Encrypted backups cannot be restored without it.</p></>}<div className="actions"><button className="button primary" disabled={busy}>Download backup</button></div></form>}
    {action === 'restore' && !backup && <form data-edit-form onSubmit={event => { event.preventDefault(); if (!backupFile) return; void act(async () => { await requireOwner(); abort.current?.abort(); const controller = new AbortController(); abort.current = controller; setBackup(await readBackupFile(backupFile, controller.signal, password)); setFormDirty(false) }) }}><p>Restore replaces all current records. Export a backup first if you need to keep them.</p><Field label="Backup file" required><input type="file" accept=".json,application/json" required aria-label="Choose backup file" onChange={event => setBackupFile(event.target.files?.[0] || null)} /></Field><Field label="Backup password" required={!!backupFile?.name.includes('.encrypted')}><input type="password" maxLength={200} required={!!backupFile?.name.includes('.encrypted')} value={password} onChange={event => setPassword(event.target.value)} autoComplete="off" /></Field><p className="form-note">Leave the password empty for an unencrypted backup.</p><div className="actions"><button className="button primary" disabled={busy}>{busy ? 'Checking backup…' : 'Check backup'}</button></div></form>}
    {(action === 'reset' || action === 'removePin' || (action === 'restore' && backup)) && <form data-edit-form onSubmit={event => { event.preventDefault(); void act(async () => { const expected = action === 'reset' ? 'RESET' : action === 'removePin' ? 'REMOVE PIN' : 'RESTORE'; if (confirm !== expected) throw new Error(`Type ${expected} exactly.`); if (action === 'reset') await resetDatabase(); else if (action === 'removePin') await setOwnerCredential(); else await restoreDatabase(backup); close(); notify(action === 'restore' ? 'Backup restored. Owner access is locked if the backup contains a PIN.' : action === 'reset' ? 'Local data reset.' : 'Owner PIN removed.') }) }}><p className="notice warning">{action === 'restore' ? `This replaces all current records with ${backup!.products.length} products, ${backup!.sales.length} sales, and ${backup!.sessions.length} days. Owner settings in the backup are also restored.` : action === 'removePin' ? 'Anyone using this app will be able to perform administrative actions.' : 'This permanently removes all local records. Export a backup first.'}</p><Field label={`Type ${action === 'reset' ? 'RESET' : action === 'removePin' ? 'REMOVE PIN' : 'RESTORE'} to confirm`} required><input data-autofocus required value={confirm} onChange={event => setConfirm(event.target.value)} autoComplete="off" /></Field><div className="actions"><button className="button danger" disabled={busy || confirm !== (action === 'reset' ? 'RESET' : action === 'removePin' ? 'REMOVE PIN' : 'RESTORE')}>{action === 'reset' ? 'Reset all local data' : action === 'removePin' ? 'Remove PIN' : 'Restore backup'}</button></div></form>}
  </Modal>}
  </>
}
